In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('online_retail_II.csv')
df = df.copy()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294749 entries, 0 to 294748
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      294749 non-null  object
 1   StockCode    294749 non-null  object
 2   Description  292686 non-null  object
 3   Quantity     294749 non-null  int64
 4   InvoiceDate  294748 non-null  object
 5   Price        294748 non-null  float64
 6   Customer ID  232094 non-null  float64
 7   Country      294748 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 18.0+ MB

In [ ]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [ ]:
df.shape

(294749, 8)

In [ ]:
df.describe(include="all")

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
count,294749,294749,292686,294749.000000,294748,294748.000000,232094.000000,294748
unique,17085,4310,4073,NaN,15022,NaN,NaN,34
top,490074,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,2009-12-03 14:39:00,NaN,NaN,United Kingdom
freq,580,2165,2180,NaN,580,NaN,NaN,273718
mean,NaN,NaN,NaN,10.533149,NaN,4.642783,15334.602053,NaN
std,NaN,NaN,NaN,110.167598,NaN,158.848505,1683.323953,NaN
min,NaN,NaN,NaN,-9200.000000,NaN,-53594.360000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,NaN,1.250000,13952.000000,NaN
50%,NaN,NaN,NaN,3.000000,NaN,2.100000,15259.000000,NaN
75%,NaN,NaN,NaN,10.000000,NaN,4.250000,16805.000000,NaN
max,NaN,NaN,NaN,19152.000000,NaN,25111.090000,18287.000000,NaN

In [ ]:
df.isnull().sum()

Invoice            0
StockCode          0
Description     2063
Quantity           0
InvoiceDate        1
Price              1
Customer ID    62655
Country            1
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(3454)

In [ ]:
df[df.duplicated()].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom

In [ ]:
df[df.duplicated(keep=False)].sort_values("Invoice").head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
669,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom

In [ ]:
# Number of completely identical rows
df.duplicated().sum()

np.int64(3454)

In [ ]:
duplicates = df[df.duplicated(keep=False)]

duplicates.sort_values(
    ["Invoice", "StockCode", "InvoiceDate"]
).head(30)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom
669,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom
721,489533,22073,RETRO SPOT STORAGE JAR,1,2009-12-01 12:02:00,3.75,16011.0,United Kingdom
723,489533,22073,RETRO SPOT STORAGE JAR,1,2009-12-01 12:02:00,3.75,16011.0,United Kingdom
716,489533,84946,ANTIQUE SILVER TEA GLASS ETCHED,6,2009-12-01 12:02:00,1.25,16011.0,United Kingdom
725,489533,84946,ANTIQUE SILVER TEA GLASS ETCHED,6,2009-12-01 12:02:00,1.25,16011.0,United Kingdom
784,489536,17164D,ASS COL SMALL SAND FROG P'WEIGHT,1,2009-12-01 12:13:00,0.42,16393.0,United Kingdom
808,489536,17164D,ASS COL SMALL SAND FROG P'WEIGHT,1,2009-12-01 12:13:00,0.42,16393.0,United Kingdom
772,489536,21034,REX CASH+CARRY JUMBO SHOPPER,1,2009-12-01 12:13:00,0.95,16393.0,United Kingdom
856,489536,21034,REX CASH+CARRY JUMBO SHOPPER,1,2009-12-01 12:13:00,0.95,16393.0,United Kingdom
826,489536,21231,SWEETHEART CERAMIC TRINKET BOX,1,2009-12-01 12:13:00,1.25,16393.0,United Kingdom

In [ ]:
duplicates.groupby(
    ["Invoice", "StockCode", "Description", "Quantity",
     "InvoiceDate", "Price", "Customer ID", "Country"]
).size().sort_values(ascending=False).head(20)

Invoice  StockCode  Description                          Quantity  InvoiceDate          Price  Customer ID  Country
496431   84826      ASSTD DESIGN 3D PAPER STICKERS       1         2010-02-01 12:30:00  0.85   16415.0      United Kingdom    6
502660   17021      NAMASTE SWAGAT INCENSE               6         2010-03-25 17:18:00  0.30   13187.0      United Kingdom    6
501425   85040B     SET/4 BLUE FLOWER CANDLES IN BOWL    1         2010-03-16 12:00:00  1.65   17774.0      United Kingdom    5
492784   22114      HOT WATER BOTTLE TEA AND SYMPATHY    1         2009-12-18 17:24:00  3.95   17841.0      United Kingdom    5
491186   85081      PADDED HOLLY CHRISTMAS DECORATION    1         2009-12-10 12:21:00  0.42   15889.0      United Kingdom    4
501922   22119      PEACE WOODEN BLOCK LETTERS           1         2010-03-22 10:26:00  6.95   13151.0      United Kingdom    4
490300   21726      MULTI HEARTS  STICKERS               1         2009-12-04 14:19:00  0.85   12970.0      United Kingdom    4
499542   22253      6 CROCHET STRAWBERRIES               1         2010-03-01 11:59:00  1.25   14131.0      United Kingdom    4
496595   22264      FELT FARM ANIMAL WHITE BUNNY         1         2010-02-02 15:49:00  0.85   13042.0      United Kingdom    4
497921   22072      TEA CUP AND SAUCER RETRO SPOT        1         2010-02-14 15:38:00  3.75   14869.0      United Kingdom    4
498352   22087      PAPER BUNTING WHITE LACE             1         2010-02-18 12:36:00  2.95   12898.0      United Kingdom    4
498999   21586      KINGS CHOICE GIANT TUBE MATCHES      1         2010-02-24 11:51:00  2.55   16406.0      United Kingdom    4
507394   84839      SWEETHEART KEY CABINET               1         2010-05-09 12:49:00  6.75   16466.0      United Kingdom    4
506388   79029      GLASS HONEYPOT WASP CATCHER          1         2010-04-29 12:51:00  1.95   16383.0      United Kingdom    4
502534   17021      NAMASTE SWAGAT INCENSE               6         2010-03-25 11:32:00  0.30   15547.0      United Kingdom    4
503774   21550      CERAMIC BIRDHOUSE CRESTED TIT LARGE  1         2010-04-07 11:04:00  5.95   14606.0      United Kingdom    4
511970   21212      PACK OF 72 RETRO SPOT CAKE CASES     1         2010-06-11 13:59:00  0.55   18022.0      United Kingdom    4
491967   22147      FELTCRAFT BUTTERFLY HEARTS           1         2009-12-14 17:34:00  1.45   17012.0      United Kingdom    4
514355   85142      JARDIN ETCHED GLASS GINGER JAR       1         2010-07-01 16:48:00  7.95   17589.0      United Kingdom    3
         85141      JARDIN ETCHED GLASS FRUITBOWL        1         2010-07-01 16:48:00  10.75  17589.0      United Kingdom    3
dtype: int64

In [ ]:
df = df.drop_duplicates()

In [ ]:
print("Rows after removing duplicates:", len(df))
print("Remaining exact duplicates:", df.duplicated().sum())

Rows after removing duplicates: 291295
Remaining exact duplicates: 0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 291295 entries, 0 to 294748
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      291295 non-null  object
 1   StockCode    291295 non-null  object
 2   Description  289232 non-null  object
 3   Quantity     291295 non-null  int64
 4   InvoiceDate  291294 non-null  object
 5   Price        291294 non-null  float64
 6   Customer ID  228694 non-null  float64
 7   Country      291294 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 20.0+ MB

In [ ]:
df.dtypes

Invoice         object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
Price          float64
Customer ID    float64
Country         object
dtype: object

In [ ]:
df["InvoiceDate"].dtype

dtype('O')

In [ ]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [ ]:
df["InvoiceDate"].dtype

dtype('<M8[ns]')

In [ ]:
df.dtypes

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
dtype: object

In [ ]:
df.isnull().sum()

Invoice            0
StockCode          0
Description     2063
Quantity           0
InvoiceDate        1
Price              1
Customer ID    62601
Country            1
dtype: int64

In [ ]:
df[df["InvoiceDate"].isna()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
294748,518115,21391,FRENCH EMROIDR LAVENDER SCENT HEART,3,NaT,NaN,NaN,NaN

In [ ]:
df[df["Price"].isna()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
294748,518115,21391,FRENCH EMROIDR LAVENDER SCENT HEART,3,NaT,NaN,NaN,NaN

In [ ]:
df[df["Country"].isna()]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
294748,518115,21391,FRENCH EMROIDR LAVENDER SCENT HEART,3,NaT,NaN,NaN,NaN

In [ ]:
df = df.dropna(subset = ["InvoiceDate" , "Price"])

In [ ]:
df.isnull().sum()

Invoice            0
StockCode          0
Description     2063
Quantity           0
InvoiceDate        0
Price              0
Customer ID    62600
Country            0
dtype: int64

In [ ]:
df[df["Description"].isna()].head(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom
6378,489882,35751C,NaN,12,2009-12-02 16:22:00,0.0,NaN,United Kingdom
6555,489898,79323G,NaN,954,2009-12-03 09:40:00,0.0,NaN,United Kingdom
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom
6581,489903,21166,NaN,48,2009-12-03 09:57:00,0.0,NaN,United Kingdom
7204,490015,21982,NaN,467,2009-12-03 12:29:00,0.0,NaN,United Kingdom
7205,490016,21982,NaN,-1012,2009-12-03 12:30:00,0.0,NaN,United Kingdom
7559,490055,20620,NaN,-25,2009-12-03 13:22:00,0.0,NaN,United Kingdom
8553,490084,85064,NaN,-89,2009-12-03 15:37:00,0.0,NaN,United Kingdom
9249,490123,84508B,NaN,184,2009-12-03 18:08:00,0.0,NaN,United Kingdom
9667,490146,21558,NaN,-169,2009-12-04 09:29:00,0.0,NaN,United Kingdom
10236,490150,84347,NaN,80,2009-12-04 09:44:00,0.0,NaN,United Kingdom
10508,490165,21493,NaN,-106,2009-12-04 11:32:00,0.0,NaN,United Kingdom
11973,490354,21489,NaN,-23,2009-12-04 16:39:00,0.0,NaN,United Kingdom
12237,490379,21490,NaN,-44,2009-12-05 13:26:00,0.0,NaN,United Kingdom

In [ ]:
df[df["Description"].isna()][["Invoice", "StockCode", "Quantity", "Price", "Customer ID", "Country"]].head(20)

      Invoice StockCode  Quantity  Price  Customer ID         Country
470    489521     21646       -50    0.0          NaN  United Kingdom
3114   489655     20683       -44    0.0          NaN  United Kingdom
3161   489659     21350       230    0.0          NaN  United Kingdom
3731   489781     84292        17    0.0          NaN  United Kingdom
4296   489806     18010      -770    0.0          NaN  United Kingdom
4566   489821    85049G      -240    0.0          NaN  United Kingdom
6378   489882    35751C        12    0.0          NaN  United Kingdom
6555   489898    79323G       954    0.0          NaN  United Kingdom
6576   489901     21098      -200    0.0          NaN  United Kingdom
6581   489903     21166        48    0.0          NaN  United Kingdom
7204   490015     21982       467    0.0          NaN  United Kingdom
7205   490016     21982     -1012    0.0          NaN  United Kingdom
7559   490055     20620       -25    0.0          NaN  United Kingdom
8553   490084     85064       -89    0.0          NaN  United Kingdom
9249   490123    84508B       184    0.0          NaN  United Kingdom
9667   490146     21558      -169    0.0          NaN  United Kingdom
10236  490150     84347        80    0.0          NaN  United Kingdom
10508  490165     21493      -106    0.0          NaN  United Kingdom
11973  490354     21489       -23    0.0          NaN  United Kingdom
12237  490379     21490       -44    0.0          NaN  United Kingdom

In [ ]:
df[df["Description"].isna()]["StockCode"].nunique()

1510

In [ ]:
missing_codes = df.loc[df["Description"].isna(), "StockCode"].unique()

df[
    df["StockCode"].isin(missing_codes) & df["Description"].notna()
][["StockCode", "Description"]].drop_duplicates().head(30)

    StockCode                          Description
1      79323P                   PINK CHERRY LIGHTS
2      79323W                  WHITE CHERRY LIGHTS
6       21871                  SAVE THE PLANET MUG
17      22142         CHRISTMAS CRAFT WHITE FAIRY
18      22296            HEART IVORY TRELLIS LARGE
19      22295            HEART FILIGREE DOVE LARGE
34      21364             PEACE SMALL WOOD LETTERS
48      22271                 FELTCRAFT DOLL ROSIE
55      21252       SET OF MEADOW  FLOWER STICKERS
73      22139    RETRO SPOT TEA SET CERAMIC 11 PC
77     16161P                   WRAP ENGLISH ROSE
82      21493             VINTAGE DESIGN GIFT TAGS
85      21731        RED TOADSTOOL LED NIGHT LIGHT
89       POST                              POSTAGE
96      21955     UNION JACK GUNS & ROSES  DOORMAT
99     84899E   YELLOW + BROWN BEAR FELT PURSE KIT
103     21582      KINGS CHOICE SMALL TUBE MATCHES
107    84251J         GREETING CARD, THE BLACK CAT
108     22024           RAINY LADIES BIRTHDAY CARD
113     21428  SET3 BOOK BOX GREEN GINGHAM FLOWER
114     21430   SET/3 RED GINGHAM ROSE STORAGE BOX
125     21041         RED SPOTTY OVEN GLOVE DOUBLE
131     22180                      RETRO SPOT LAMP
135     22253               6 CROCHET STRAWBERRIES
140     21299          EDWARDIAN TOILET ROLL UNIT
141     21099          SET/6 STRAWBERRY PAPER CUPS
142     21085            SET/6 WOODLAND PAPER CUPS
143     21929       JUMBO BAG PINK VINTAGE PAISLEY
145     21091          SET/6 WOODLAND PAPER PLATES
149     22125         UNION JACK HOT WATER BOTTLE

In [ ]:
description_mapping = (
    df[df["Description"].notna()]
    .groupby("StockCode")["Description"]
    .nunique()
)

description_mapping.sort_values(ascending=False).head(20)

StockCode
84016     4
21955     4
22236     4
47566B    4
22607     3
84918     3
84937     3
17129F    3
22423     3
47591C    3
84807     3
21843     3
84078A    3
22359     3
22360     3
22719     3
84508A    3
46000R    3
48173C    3
22343     3
Name: Description, dtype: int64

In [ ]:
(description_mapping > 1).sum()

np.int64(348)

In [ ]:
conflicting_codes = description_mapping[description_mapping > 1].index

df[
    df["StockCode"].isin(conflicting_codes) &
    df["Description"].notna()
][["StockCode", "Description"]].drop_duplicates().head(50)

    StockCode                         Description
2      79323W                 WHITE CHERRY LIGHTS
7       21523  FANCY FONT HOME SWEET HOME DOORMAT
8       22350                           CAT BOWL
9       22349      DOG BOWL , CHASING BALL DESIGN
10      22195        HEART MEASURING SPOONS LARGE
11      22353  LUNCHBOX WITH CUTLERY FAIRY CAKES
12     48173C               DOOR MAT BLACK FLOCK
15      84879       ASSORTED COLOUR BIRD ORNAMENT
16      22119          PEACE WOODEN BLOCK LETTERS
25      21181       PLEASE ONE PERSON  METAL SIGN
33      22130    PARTY CONE CHRISTMAS DECORATION
56      21100      CHARLIE AND LOLA CHARLOTTE BAG
73      22139   RETRO SPOT TEA SET CERAMIC 11 PC
74      22352    LUNCHBOX WITH CUTLERY RETROSPOT
82      21493            VINTAGE DESIGN GIFT TAGS
96      21955    UNION JACK GUNS & ROSES  DOORMAT
99     84899E  YELLOW + BROWN BEAR FELT PURSE KIT
102    85123A  WHITE HANGING HEART T-LIGHT HOLDER
110     22029             SPACE BOY BIRTHDAY CARD
125     21041        RED SPOTTY OVEN GLOVE DOUBLE
143     21929      JUMBO BAG PINK VINTAGE PAISLEY
144     22241   GARLAND , WOODEN  " HAPPY EASTER"
146     21733    RED HANGING HEART T-LIGHT HOLDER
150     21671        RED SPOT CERAMIC DRAWER KNOB
161    85099B         JUMBO BAG RED WHITE SPOTTY
162     22356    CHARLOTTE BAG , PINK/WHITE SPOTS
171     22195        LARGE HEART MEASURING SPOONS
216     22232           3 PIECE JIGSAW TOADSTOOLS
221    79323S                SILVER CHERRY LIGHTS
241    82494L         WOODEN FRAME ANTIQUE WHITE
249     72756                  FAIRY CAKE CANDLES
251     37450   CERAMIC CAKE BOWL + HANGING CAKES
263     21733                        85123a mixed
277     48185                 DOOR MAT FAIRY CAKE
283     71477                               short
284    85123A                         21733 mixed
316     21540      DAIRY MAID CERAMIC BUTTER DISH
322    47566B              TEA TIME PARTY BUNTING
332     71477   COLOUR GLASS. STAR T-LIGHT HOLDER
338    47591D       PINK FAIRY CAKE CHILD'S APRON
376    47591A          CAROUSEL DES CHILD'S APRON
388    84951A     S/4 PISTACHIO LOVEBIRD COASTERS
421     21133     PAINTED BIRD ASSORTED CHRISTMAS
441    72739B        WHITE CHOCOLATE SCENT CANDLE
445     48187                DOOR MAT NEW ENGLAND
446     48195             DOOR MAT GREEN PAISLEY
447     72741               GRAND CHOCOLATECANDLE
523     48111              DOOR MAT 3 SMILEY CATS
524     20685             RED SPOTTY COIR DOORMAT
525     48194                      DOORMAT HEARTS

In [ ]:
conflict_counts = (
    df[df["StockCode"].isin(conflicting_codes) & df["Description"].notna()]
    .groupby(["StockCode", "Description"])
    .size()
    .sort_values(ascending=False)
)

conflict_counts.head(30)

StockCode  Description
85123A     WHITE HANGING HEART T-LIGHT HOLDER     2138
22423      REGENCY CAKESTAND 3 TIER               1049
84879      ASSORTED COLOUR BIRD ORNAMENT           779
47566      PARTY BUNTING                           747
82494L     WOODEN FRAME ANTIQUE WHITE              701
48138      DOOR MAT UNION FLAG                     678
22384      LUNCH BAG PINK RETROSPOT                660
22383      LUNCH BAG SUKI  DESIGN                  642
22139      RETRO SPOT TEA SET CERAMIC 11 PC        627
22382      LUNCH BAG SPACEBOY DESIGN               609
21733      RED HANGING HEART T-LIGHT HOLDER        560
85099B     JUMBO BAG RED WHITE SPOTTY              550
37503      TEA TIME CAKE STAND IN GIFT BOX         531
22326      ROUND SNACK BOXES SET OF4 WOODLAND      499
71459      HANGING JAM JAR T-LIGHT HOLDER          489
48187      DOOR MAT NEW ENGLAND                    466
85099B     JUMBO BAG RED RETROSPOT                 451
21929      JUMBO BAG PINK VINTAGE PAISLEY          434
22558      CLOTHES PEGS RETROSPOT PACK 24          423
20685      DOOR MAT RED SPOT                       415
20713      JUMBO BAG OWLS                          399
15056N     EDWARDIAN PARASOL NATURAL               392
48185      DOOR MAT FAIRY CAKE                     392
47591D     PINK FAIRY CAKE CHILD'S APRON           390
22328      ROUND SNACK BOXES SET OF 4 FRUITS       390
21843      RETRO SPOT CAKE STAND                   387
22470      HEART OF WICKER LARGE                   379
21843      RED RETROSPOT CAKE STAND                375
22607      WOODEN ROUNDERS GARDEN SET              374
72741      GRAND CHOCOLATECANDLE                   367
dtype: int64

In [ ]:
description_mode = (
    df[df["Description"].notna()]
    .groupby("StockCode")["Description"]
    .agg(lambda x: x.mode().iloc[0])
)

missing_description_codes = df.loc[
    df["Description"].isna(), "StockCode"
]

missing_codes_recoverable = missing_description_codes.isin(
    description_mode.index
).sum()

missing_codes_total = missing_description_codes.nunique()

print("Missing description rows:", df["Description"].isna().sum())
print("Unique StockCodes with missing description:", missing_codes_total)
print("Missing rows with recoverable StockCode:", missing_codes_recoverable)

Missing description rows: 2063
Unique StockCodes with missing description: 1510
Missing rows with recoverable StockCode: 1694

In [ ]:
description_mode = (
    df[df["Description"].notna()]
    .groupby("StockCode")["Description"]
    .agg(lambda x: x.mode().iloc[0])
)

df["Description"] = df["Description"].fillna(
    df["StockCode"].map(description_mode)
)

In [ ]:
print("Missing descriptions:", df["Description"].isna().sum())

Missing descriptions: 363

In [ ]:
df[df["Description"].isna()][
    ["Invoice", "StockCode", "Quantity", "Price",
     "Customer ID", "Country"]
].head(30)
df[df["Description"].isna()]["StockCode"].value_counts().head(20)

StockCode
35983           2
84494B          2
37477D          2
84933D          2
gift_0001_90    2
21502           2
gift_0001_60    2
84558B          2
21295           1
84896C          1
84866           1
84248F          1
84449           1
72801H          1
71265           1
16249B          1
84476A          1
84394           1
82595           1
79053D          1
Name: count, dtype: int64

In [ ]:
missing_desc = df[df["Description"].isna()]

missing_desc[
    ["Invoice", "StockCode", "Quantity", "Price",
     "Customer ID", "Country"]
].head(30)

      Invoice StockCode  Quantity  Price  Customer ID         Country
470    489521     21646       -50    0.0          NaN  United Kingdom
16186  490736     35983      -200    0.0          NaN  United Kingdom
19313  490976     84571      -120    0.0          NaN  United Kingdom
20975  491066     35949       -67    0.0          NaN  United Kingdom
22854  491167    17013A       -45    0.0          NaN  United Kingdom
23542  491206     84841       -54    0.0          NaN  United Kingdom
32106  491975    72752C       -24    0.0          NaN  United Kingdom
32109  491977    72755B       -23    0.0          NaN  United Kingdom
32110  491976    72752D       -46    0.0          NaN  United Kingdom
43528  493138    35751A       152    0.0          NaN  United Kingdom
43583  493150    71263G        39    0.0          NaN  United Kingdom
43623  493162     20691        20    0.0          NaN  United Kingdom
43625  493164     20880        17    0.0          NaN  United Kingdom
43626  493165     20859        15    0.0          NaN  United Kingdom
43629  493169     72777        14    0.0          NaN  United Kingdom
43635  493170    79069A        14    0.0          NaN  United Kingdom
43640  493178    84247B        11    0.0          NaN  United Kingdom
43641  493179    84986A        11    0.0          NaN  United Kingdom
43687  493185    35980A         9    0.0          NaN  United Kingdom
43688  493184     84940        10    0.0          NaN  United Kingdom
43689  493186    79053A         9    0.0          NaN  United Kingdom
43780  493192    72655C         8    0.0          NaN  United Kingdom
43782  493193    35977B         7    0.0          NaN  United Kingdom
43799  493199    35975B         6    0.0          NaN  United Kingdom
43801  493203     20959         5    0.0          NaN  United Kingdom
43804  493206    85231D         5    0.0          NaN  United Kingdom
43806  493205    85025A         5    0.0          NaN  United Kingdom
43807  493208     21492         4    0.0          NaN  United Kingdom
43808  493207     21362         4    0.0          NaN  United Kingdom
43810  493211     35994         4    0.0          NaN  United Kingdom

In [ ]:
missing_desc[["Quantity", "Price"]].describe()

          Quantity  Price
count   363.000000  363.0
mean    -44.201102    0.0
std     327.616760    0.0
min   -4999.000000    0.0
25%     -23.000000    0.0
50%      -7.000000    0.0
75%      -1.000000    0.0
max     160.000000    0.0

In [ ]:
missing_desc["Price"].value_counts()

Price
0.0    363
Name: count, dtype: int64

In [ ]:
df["Price"].value_counts().head(10)

Price
1.25    104428
1.65     73808
0.85     69218
2.95     65862
0.42     45438
2.10     42398
3.75     40313
4.95     35336
1.95     34138
2.55     31811
Name: count, dtype: int64

In [ ]:
(df["Price"] == 0).sum()

np.int64(6202)

In [ ]:
(df["Quantity"] < 0).sum()

np.int64(22950)

In [ ]:
df["TransactionType"] = np.where(
    df["Quantity"] < 0,
    "Return",
    "Sale"
)

In [ ]:
df["Revenue"] = df["Quantity"] * df["Price"]

In [ ]:
df[["Quantity", "Price", "Revenue"]].head()

   Quantity  Price  Revenue
0        12   6.95     83.4
1        12   6.75     81.0
2        12   6.75     81.0
3        48   2.10    100.8
4        24   1.25     30.0

In [ ]:
print("Shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())
print("\nMissing values:")
print(df.isnull().sum())

Shape: (1067371, 10)
Duplicate rows: 34335

Missing values:
Invoice                 0
StockCode               0
Description          4382
Quantity                0
InvoiceDate             0
Price                   0
Customer ID        243007
Country                 0
TransactionType         0
Revenue                 0
dtype: int64

In [ ]:
# 1. Remove exact duplicate rows
df = df.drop_duplicates()

# 2. Remove rows with unusable date/price/country
df = df.dropna(subset=["InvoiceDate", "Price", "Country"])

# 3. Fill missing descriptions where StockCode has a known description
description_mode = (
    df[df["Description"].notna()]
    .groupby("StockCode")["Description"]
    .agg(lambda x: x.mode().iloc[0])
)

df["Description"] = df["Description"].fillna(
    df["StockCode"].map(description_mode)
)

# 4. Recalculate transaction type and revenue
df["TransactionType"] = np.where(
    df["Quantity"] < 0, "Return", "Sale"
)

df["Revenue"] = df["Quantity"] * df["Price"]

In [ ]:
print("Final shape:", df.shape)
print("Duplicates:", df.duplicated().sum())
print("Missing values:")
print(df.isnull().sum())

Final shape: (1033036, 10)
Duplicates: 0
Missing values:
Invoice                 0
StockCode               0
Description           363
Quantity                0
InvoiceDate             0
Price                   0
Customer ID        235151
Country                 0
TransactionType         0
Revenue                 0
dtype: int64

In [ ]:
expected_shape = (1033036, 10)
current_shape = df.shape

if current_shape == expected_shape:
    print(f"DataFrame shape matches the expected shape: {current_shape}")
    output_filename = 'online_retail_II_cleaned.csv'
    df.to_csv(output_filename, index=False)
    print(f"DataFrame successfully exported to {output_filename}")

    # Verify file creation and provide download link
    import os
    if os.path.exists(output_filename):
        print(f"File '{output_filename}' created successfully. You can download it using the file browser on the left or programmatically below:")
        from google.colab import files
        files.download(output_filename)
    else:
        print(f"Error: File '{output_filename}' was not created.")
else:
    print(f"DataFrame shape mismatch. Expected {expected_shape}, but got {current_shape}.")

DataFrame shape matches the expected shape: (1033036, 10)
DataFrame successfully exported to online_retail_II_cleaned.csv
File 'online_retail_II_cleaned.csv' created successfully. You can download it using the file browser on the left or programmatically below:

In [ ]:
df2 = pd.read_csv("online_retail_II_cleaned (1).csv")

### Querying DataFrame with SQL using `pandasql`

Since you're working with pandas DataFrames, you can treat them like SQL tables using the `pandasql` library. First, we'll install the library, then import it, and finally demonstrate how to run a SQL query on your `df2` DataFrame.

In [ ]:
# Install pandasql
!pip install pandasql

Requirement already satisfied: pandasql in /usr/local/lib/python3.13/dist-packages (0.7.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from pandasql) (2.1.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from pandasql) (2.2.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (from pandasql) (2.0.52)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->pandasql) (2026.3)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy->pandasql) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy->pandasql) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)

In [ ]:
from pandasql import sqldf

# Define a simple SQL query. The DataFrame name 'df2' is used as the table name.
query = """
SELECT
    Country,
    COUNT(DISTINCT `Customer ID`) AS unique_customers,
    SUM(Revenue) AS total_revenue
FROM
    df2
GROUP BY
    Country
ORDER BY
    total_revenue DESC
LIMIT 10;
"""

# Execute the SQL query on the DataFrame
result_df = sqldf(query, globals())

# Display the results
display(result_df)

          Country  unique_customers  total_revenue
0  United Kingdom              5410   1.598606e+07
1            EIRE                 5   6.099538e+05
2     Netherlands                23   5.483307e+05
3         Germany               107   4.119592e+05
4          France                95   3.217334e+05
5       Australia                15   1.664444e+05
6     Switzerland                22   9.940306e+04
7           Spain                41   9.101344e+04
8          Sweden                19   8.777552e+04
9         Denmark                12   6.445959e+04

In [ ]:
query = """ select sum(Revenue)
from df2 """

In [ ]:
from pandasql import sqldf

# Execute the SQL query on the DataFrame
result_total_revenue = sqldf(query, globals())

# Display the results
display(result_total_revenue)

   sum(Revenue)
0  1.885553e+07

In [ ]:
from pandasql import sqldf

# Define your SQL query directly as a string
new_sql_query = """
SELECT
    StockCode,
    SUM(Quantity) AS total_quantity_sold
FROM
    df2
GROUP BY
    StockCode
ORDER BY
    total_quantity_sold DESC
LIMIT 5;
"""

# Execute the query using sqldf and display the result
result_stock_quantity = sqldf(new_sql_query, globals())
display(result_stock_quantity)

# Alternatively, if you want to use the helper function we defined:
# run_sql_query(new_sql_query)

In [ ]:
from pandasql import sqldf

def run_sql_query(sql_query_string, dataframe_vars=globals()):
    """
    Executes a SQL query against the DataFrames available in dataframe_vars
    and displays the result.
    """
    print(f"Executing query:\n{sql_query_string}")
    result = sqldf(sql_query_string, dataframe_vars)
    display(result)
    return result

Now, you can use this `run_sql_query` function. For example, to get the sum of revenue again, or to find the average quantity per country:

In [ ]:
# Example 1: Get the sum of Revenue using the helper function
query_sum_revenue = """SELECT sum(Revenue) FROM df2"""
run_sql_query(query_sum_revenue)

# Example 2: Find the average Quantity per Country
query_avg_quantity = """
SELECT
    Country,
    AVG(Quantity) AS average_quantity
FROM
    df2
GROUP BY
    Country
ORDER BY
    average_quantity DESC
LIMIT 5;
"""
run_sql_query(query_avg_quantity)

Executing query:
SELECT sum(Revenue) FROM df2

   sum(Revenue)
0  1.885553e+07

Executing query:

SELECT
    Country,
    AVG(Quantity) AS average_quantity
FROM
    df2
GROUP BY
    Country
ORDER BY
    average_quantity DESC
LIMIT 5;

       Country  average_quantity
0      Denmark        294.559598
1      Bermuda         82.294118
2  Netherlands         74.333852
3       Sweden         64.506608
4    Australia         54.695767

       Country  average_quantity
0      Denmark        294.559598
1      Bermuda         82.294118
2  Netherlands         74.333852
3       Sweden         64.506608
4    Australia         54.695767